In [4]:
x = 2
y = 3

del x 


In [1]:
print(x)


NameError: name 'x' is not defined

In [2]:
x = 10
y = 3

u = x + y
v = x * y
w = x / y

import math
z = math.sin(x)
r = 8 * math.sin(x)
s = 5 * math.sin(x * y)
p = x ** y

u, v, w, z, r, s, p

(13,
 30,
 3.3333333333333335,
 -0.5440211108893698,
 -4.352168887114958,
 -4.940158120464309,
 1000)

In [3]:
S = '123'

N = float(S)

type(S), type(N)

(str, float)

In [4]:
s1 = 'HELLO'
s2 = 'hello'

s1 == s2, s1.lower() == s2, s1 == s2.upper()


(False, True, True)

In [5]:
print(f"The word 'Engineering' has {len('Engineering')} letters.")
print(f"The word 'Book' has {len('Book')} letters.")

The word 'Engineering' has 11 letters.
The word 'Book' has 4 letters.


In [6]:
'Python is great!'.split()[-1]

'great!'

In [7]:
'Python' in 'Python is great!'

True

In [8]:
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)
list_a

[1, 2, 8, 9, 15, 4]

In [9]:
list_a.sort()
list_a

[1, 2, 4, 8, 9, 15]

In [10]:
import numpy as np

array = np.linspace(-10, 10, 100)
array

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [11]:
array_a = np.array([-1, 0, 1, 2, 0, 3])
array_a[array_a > 0]

array([1, 2, 3])

In [12]:
y = np.array([[3, 2, 3], [5, 2, 8], [3, 5, 9]])
y.T

array([[3, 5, 3],
       [2, 2, 5],
       [3, 8, 9]])

In [13]:
zero_array = np.zeros((2, 4))
zero_array[:, 1] = 1
zero_array

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [14]:
%reset -f