In [1]:
import math

def my_sinh(x):
    y = (math.exp(x) - math.exp(-x)) / 2
    return y

In [6]:
my_sinh(2)

3.626860407847019

In [7]:
import numpy as np

def my_checker_board(n):
    m = np.zeros((n, n), dtype=int)  
    m[::2, ::2] = 1  
    m[1::2, 1::2] = 1 
    return m

In [12]:
my_checker_board(5)

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [13]:
def my_triangle(b, h):
    return 0.5 * b * h

In [16]:
my_triangle(12,5)

30.0

In [18]:
def my_split_matrix(m):
    n_cols = m.shape[1]  # Number of columns
    split_col = (n_cols + 1) // 2  # Column to split at (middle column goes to m1 if odd)
    
    m1 = m[:, :split_col]  # Left half including the middle column if odd
    m2 = m[:, split_col:]  # Right half excluding the middle column if odd
    
    return m1, m2


In [25]:

m1, m2 = my_split_matrix(np.ones((5, 5)))
m1 ,m2

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]))

In [30]:
def my_cylinder(r, h):
    s = 2 * np.pi * r * (r + h)
    v = np.pi * r**2 * h
    return [round(s, 4), round(v, 4)]

In [33]:
my_cylinder(2,4)

[75.3982, 50.2655]

In [34]:
def my_n_odds(a):
    odd_count = np.sum(a % 2 != 0)
    return odd_count

In [36]:
my_n_odds(np.arange(2, 100, 2))

0

In [37]:
def my_twos(m, n):
    return np.ones((m, n)) * 2

In [39]:
my_twos(1, 4)

array([[2., 2., 2., 2.]])

In [43]:
def add_string(s1, s2):
    return s1 + ' ' + s2

In [46]:
s1 = add_string('Programming','is')
s2 = add_string('fun', '!')
result = add_string(s1, s2)
result

'Programming is fun !'

In [47]:
def greeting(name, age):
    return f'Hi, my name is {name} and I am {age} years old.'

In [49]:
greeting('Kate', 19)

'Hi, my name is Kate and I am 19 years old.'

In [50]:
def my_donut_area(r1, r2):
    area = np.pi * (r2**2 - r1**2)
    return area

In [51]:
my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

array([ 9.42477796, 37.69911184, 84.82300165])

In [58]:

def my_within_tolerance(A, a, tol):
    A = np.array(A)
    indices = np.where(np.abs(A - a) < tol)[0]
    return indices.tolist()

In [60]:
res =  my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)
res

[47, 48, 49, 50, 51, 52]

In [61]:

def bounding_array(A, top, bottom):
    B = A.copy()
    B[B < bottom] = bottom
    B[B > top] = top
    return B

In [62]:
res = bounding_array(np.arange(-5, 6, 1), 3, -3)
res

array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3,  3])